name: Alerta DevOps

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificacion a ntfy
        run: |
          curl -H "Title: GitHub Actions" \
               -H "Priority: default" \
               -d "Se realizo un push a la rama main del repositorio ${{ github.repository }}" \
               https://ntfy.sh/devops-itla
